apiVersion: v1
kind: Service
metadata:
  name: skhappycampus-mailserver-service
spec:
  ports:
  - name: "http"
    port: 8025
    targetPort: 8025
    nodePort: 30025
  - name: "smtp"
    port: 25
    targetPort: 25
  selector:
    run: skhappycampus-mailserver
  type: NodePort
